FROM node:22-alpine AS build

WORKDIR /app

ARG VITE_API_BASE_URL
ARG VITE_API_USERNAME
ARG VITE_API_PASSWORD
ARG VITE_PHOTO_BOOTH_ID
ARG VITE_PUBLIC_WEB_BASE_URL
ARG VITE_CAMERA_CONTROL_ENABLED
ARG VITE_CAMERA_CONTROL_BASE_URL
ARG VITE_CAMERA_APP_PATH

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_USERNAME=$VITE_API_USERNAME
ENV VITE_API_PASSWORD=$VITE_API_PASSWORD
ENV VITE_PHOTO_BOOTH_ID=$VITE_PHOTO_BOOTH_ID
ENV VITE_PUBLIC_WEB_BASE_URL=$VITE_PUBLIC_WEB_BASE_URL
ENV VITE_CAMERA_CONTROL_ENABLED=$VITE_CAMERA_CONTROL_ENABLED
ENV VITE_CAMERA_CONTROL_BASE_URL=$VITE_CAMERA_CONTROL_BASE_URL
ENV VITE_CAMERA_APP_PATH=$VITE_CAMERA_APP_PATH

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund

COPY . .
RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -q --spider http://127.0.0.1/ || exit 1

CMD ["nginx", "-g", "daemon off;"]
